#!/usr/bin/env bash
#linux
now=$(date +'%s' )

if [ -e "/proc/loadavg" ]; then
    for (( i ; i<1;i++)); do
        echo $now:$( hostname ):cpu.load:$( cat /proc/loadavg | cut -d " " -f $(( i + 1 )) ):GAUGE
    done
fi
# BSD
if $( sysctl vm.loadavg &>/dev/null ); then
    for (( i=0 ; i<1;i++)); do
            echo $now:$( hostname ):cpu.load:$( sysctl vm.loadavg | cut -d " " -f $(( i + 3 )) ):GAUGE
    done
fi
