#!/bin/sh
now=$(date +'%s' )

: <<EOF

=head1 NAME

tcp - Plugin to monitor IPV4/6 TCP socket status on a Linux host.

=head1 LICENSE

GPLv2

=cut

EOF


# See #include <netinet/tcp.h>
HOST=$( hostname )
if [ -e /proc/net ]; then
	cat /proc/net/tcp* | awk " 

	  match (\$4, /0[0-9A-B]/) {
	      STATE[\$4]++;
	  }

	  END {
	      printf \"$HOST:$now:tcp.established:%d:GAUGE\n\", STATE[\"01\"];
	      printf \"$HOST:$now:tcp.syn_sent:%d:GAUGE\n\",    STATE[\"02\"];
	      printf \"$HOST:$now:tcp.syn_recv:%d:GAUGE\n\",    STATE[\"03\"];
	      printf \"$HOST:$now:tcp.fin_wait1:%d:GAUGE\n\",   STATE[\"04\"];
	      printf \"$HOST:$now:tcp.fin_wait2:%d:GAUGE\n\",   STATE[\"05\"];
	      printf \"$HOST:$now:tcp.time_wait:%d:GAUGE\n\",   STATE[\"06\"];
	      printf \"$HOST:$now:tcp.close:%d:GAUGE\n\",       STATE[\"07\"];
	      printf \"$HOST:$now:tcp.close_wait:%d:GAUGE\n\",  STATE[\"08\"];
	      printf \"$HOST:$now:tcp.last_ack:%d:GAUGE\n\",    STATE[\"09\"];
	      printf \"$HOST:$now:tcp.listen:%d:GAUGE\n\",      STATE[\"0A\"];
	      printf \"$HOST:$now:tcp.closing:%d:GAUGE\n\",     STATE[\"0B\"];
	  }"
fi
